version: 2.1

parameters:

  api:
    type: boolean
    default: false

references:

  working_dir: &working_dir
                 ~/project

executors:
  jdk_executor:
    working_directory: *working_dir
    docker:
      - image: cimg/openjdk:11.0
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.caching=true

orbs:
  # https://circleci.com/developer/orbs/orb/eddiewebb/queue
  queue: eddiewebb/queue@1.5.0

commands:

  attach_to_workspace:
    steps:
      - attach_workspace:
          at: ~/

  persist_gradle_build_cache:
    steps:
      - persist_to_workspace:
          root: ~/
          paths:
            - gradle-build-cache

jobs:

  ktlint:
    executor: jdk_executor
    steps:
      - checkout
      - run:
          name: Ktlint
          command: ./gradlew ktlint --stacktrace

  security:
    executor: jdk_executor
    steps:
      - checkout
      - run:
          name: Verify the integrity of the Gradle Wrapper JAR
          command: |
            # https://docs.gradle.org/current/userguide/gradle_wrapper.html#wrapper_checksum_verification
            cd gradle/wrapper
            gradleVersion=$(grep "distributionUrl" gradle-wrapper.properties | grep -Po "(\d+\.)+\d+")
            curl --location --output gradle-wrapper.jar.sha256 https://services.gradle.org/distributions/gradle-${gradleVersion}-wrapper.jar.sha256
            echo "  gradle-wrapper.jar" >> gradle-wrapper.jar.sha256
            sha256sum --check gradle-wrapper.jar.sha256

  build:
    executor: jdk_executor
    steps:
      - checkout
      - attach_to_workspace
      - run:
          name: Assemble
          command: ./gradlew assemble --stacktrace
      - persist_gradle_build_cache
      - store_artifacts:
          path: ./build/libs
          destination: jars

  test:
    executor: jdk_executor
    steps:
      - checkout
      - attach_to_workspace
      - run:
          name: Run tests
          command: ./gradlew test --stacktrace
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ./build/reports/tests/test
          destination: tests

  validatePlugins:
    executor: jdk_executor
    steps:
      - checkout
      - attach_to_workspace
      - run:
          name: Validate plugins
          command: ./gradlew validatePlugins --stacktrace

  publish:
    executor: jdk_executor
    steps:
      - checkout
      - attach_to_workspace
      - queue/until_front_of_line:
          block-workflow: true
          only-on-branch: master
      - run:
          name: Uploading to Nexus Sonatype
          command: ./gradlew publish -PLOCAL_UPLOAD=false --refresh-dependencies --stacktrace

workflows:
  commit:
    unless: << pipeline.parameters.api >>
    jobs:
      - security
      - ktlint
      - build
      - test:
          requires:
            - build
      - validatePlugins:
          requires:
            - build
      - publish:
          filters:
            branches:
              only:
                - master
                - production
          requires:
            - ktlint
            - test
            - validatePlugins
            - security
